name: Go

on:
  push:
    branches: [ B1 ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: cd server/cmd/main
      run: go build -v ./...

    - name: Test
      run: cd server/cmd/main
      run: go test -v ./...